version: 2

jobs:
  macos:
    macos:
      xcode: "11.3.1"
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: swift:5.1
    steps:
      - run: apt-get install -y libssl-dev
      - checkout
      - run: swift build
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - macos
